/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Norimaki(props) {
  const { nodes, materials } = useGLTF('/models/shoe3/norimaki.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.26, 0.01, -0.05]} rotation={[0, 1.56, 0]} scale={0.49}>
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020.geometry} material={materials.Mainc} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_1.geometry} material={materials.Patch} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_2.geometry} material={materials.Foxing} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_3.geometry} material={materials.Pulltab} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_4.geometry} material={materials.Slip} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_5.geometry} material={materials.Midsole} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_6.geometry} material={materials.Outsole} />
        <mesh geometry={nodes.Shs_SHI014__M_SHI014020_7.geometry} material={materials.Insole} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/shoe3/norimaki.gltf')
