/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sandal(props) {
  const { nodes, materials } = useGLTF('/models/slipper3/sandal.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.16, 0.05, 0]} rotation={[0, 1.56, 0]} scale={[-0.52, 0.52, 0.52]}>
        <mesh geometry={nodes.Sandals_1.geometry} material={materials.Footbed} />
        <mesh geometry={nodes.Sandals_2.geometry} material={materials.Strap} />
        <mesh geometry={nodes.Sandals_3.geometry} material={materials.Backstrap} />
        <mesh geometry={nodes.Sandals_4.geometry} material={materials.Midsole} />
        <mesh geometry={nodes.Sandals_5.geometry} material={materials.Outsole} />
        <mesh geometry={nodes.Sandals_6.geometry} material={materials.Patch} />
        <mesh geometry={nodes.Sandals_7.geometry} material={materials.Holder} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/slipper3/sandal.gltf')
